---
title: "Super Bowl History Analysis"
description: |
  Welcome to the website. I hope you enjoy it!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

library(tidyverse)
library(dplyr)
library(plotly)
library(gridExtra)
library(ggplot2)
library(ggthemes)
library(ggpubr)
```

```{r}

s <- read_csv("~/Downloads/superbowl.csv")
s
superbowlrow <- c("Feb 7 2021", "LV (55)", "Tampa Bay Buccaneers", 31.0, "Kansas City Chiefs", 9.0, "Tom Brady", "Raymond James Stadium", "Tampa Bay", "Florida")
superbowl <- rbind(superbowlrow, s)   
superbowl$`Winner Pts` <- as.integer(superbowl$`Winner Pts`)
superbowl$`Loser Pts` <- as.integer(superbowl$`Loser Pts`)

```

```{r}
count_of_states <- superbowl %>%
  group_by(State)
count_of_states%>%
  summarize(total = n()) 
ggplot(data = count_of_states, aes(x = State)) + 
  geom_bar(color = "black", fill = "maroon") +
  theme(panel.background = element_rect(fill = "light blue")) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_y_continuous(breaks = seq(0, 20, by = 2)) + 
  labs(x = "Super Bowl Host States", y = "Number of Super Bowl Games Hosted", title = "Which States Have Hosted More Games?", subtitle = "Florida has hosted the most Super Bowl games, while Indiana and New Jersey each have hosted once")  +
  theme(plot.subtitle = element_text(size = 10))

```
```{r fig.width = 15, fig.height=10}
deficits_states <- superbowl %>%
  mutate(deficit = `Winner Pts` - `Loser Pts`)%>%
  mutate(Date = str_sub(Date, -4))
deficits_states$Date <- as.numeric(deficits_states$Date)
ggplot(data = deficits_states, aes(x = State, y = deficit, fill = State)) + 
geom_boxplot(outlier.colour="black", outlier.shape=16, outlier.size=2, notch=FALSE) +
  geom_point(alpha = 0.1) + 
  theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 20), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), legend.text = element_text(size = 16), legend.title = element_text(size = 16))
```

```{r}
trends <- superbowl %>%
  mutate(Date = str_sub(Date, -4))
trends$Date = as.numeric(trends$Date)
x <- trends %>%
  ggplot(aes(x = Date, y = `Winner Pts`, group = 1, color = State)) + 
  geom_point()
y <- trends %>%
  ggplot(aes(x = Date, y = `Loser Pts`, group = 1)) + 
  geom_point() 
deficits <- deficits_states %>%
  ggplot(aes(x = Date, y = deficit, group = 1, color = State, text = paste(Winner))) + 
  geom_point() +
  scale_x_continuous(breaks = seq(1970, 2021, by = 5)) + 
  scale_y_continuous(breaks = seq(0, 50, by = 5)) 
def <- deficits_states %>%
  ggplot(aes(x = Date, y = deficit, group = 1, text = paste(Winner))) + 
  geom_line() +
  scale_x_continuous(breaks = seq(1970, 2021, by = 5)) + 
  scale_y_continuous(breaks = seq(0, 50, by = 5))


ggplotly(deficits)
```

```{r}
ggplotly(def)
```
```{r}
categories <- deficits_states
categories <- categories%>%
  mutate(year_ints = case_when(
    (Date < 1981 & Date > 1970) ~ "1970-1980",
    (Date < 1991 & Date > 1980) ~ "1980-1990",
    (Date < 2001 & Date > 1990) ~ "1990-2000",
    (Date < 2011 & Date > 2000) ~ "2000-2010",
    (Date < 2021 & Date > 2010) ~ "2010-2020",
  ))%>%
  na.omit()%>%
  group_by(year_ints)%>%
  select(deficit, year_ints)%>%
  summarise_at(vars(deficit),              
               list(`Mean Deficits` = mean)) 
categories%>%
  ggplot(aes(x = year_ints, y = `Mean Deficits`)) + 
  geom_bar(stat = "identity") +
    stat_summary(fun.y=sum,geom="bar",colour="black",fill="#CC6666",show.legend = FALSE) + 
  labs(x = "10-Year Period", y = "Mean Deficits", title = "Which 10-Year Period Had More Lopsided Games?") + 
  theme_classic()

```

```{r}
categories2 <- deficits_states
categories2 <- categories2%>%
  mutate(year_ints = case_when(
    (Date < 1976 & Date > 1970) ~ "1970-1975",
    (Date < 1981 & Date > 1975) ~ "1975-1980",
    (Date < 1986 & Date > 1980) ~ "1980-1985",
    (Date < 1991 & Date > 1985) ~ "1985-1990",
    (Date < 1996 & Date > 1990) ~ "1990-1995",
    (Date < 2001 & Date > 1995) ~ "1995-2000",
    (Date < 2006 & Date > 2000) ~ "2000-2005",
    (Date < 2011 & Date > 2005) ~ "2005-2010",
    (Date < 2016 & Date > 2010) ~ "2010-2015",
    (Date < 2021 & Date > 2015) ~ "2015-2020",
  ))%>%
  na.omit()%>%
  group_by(year_ints)%>%
  select(deficit, year_ints)%>%
  summarise_at(vars(deficit),              
               list(`Mean Deficits` = mean))

```

```{r}
categories2%>%
  ggplot(aes(x = year_ints, y = `Mean Deficits`)) + 
  geom_bar(stat = "identity") +
    stat_summary(fun.y=sum,geom="bar",colour="black",fill="#92A8D1",show.legend = FALSE) +
    labs(x = "5-Year Period", y = "Mean Deficits", title = "Which 5-Year Period Had More Lopsided Games?") + 
    theme(axis.text.x = element_text(size = 8)) + 
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(panel.background = element_blank()) + 
  theme(axis.line = element_line(color="black", size = 0.5))


```
```{r}
total_points <- superbowl%>%
  mutate(Date = str_sub(Date, -4))
total_points$Date <- as.numeric(total_points$Date)
total_points <- total_points%>%
  mutate(year_ints_by_5 = case_when(
    (Date < 1976 & Date > 1970) ~ "1970-1975",
    (Date < 1981 & Date > 1975) ~ "1975-1980",
    (Date < 1986 & Date > 1980) ~ "1980-1985",
    (Date < 1991 & Date > 1985) ~ "1985-1990",
    (Date < 1996 & Date > 1990) ~ "1990-1995",
    (Date < 2001 & Date > 1995) ~ "1995-2000",
    (Date < 2006 & Date > 2000) ~ "2000-2005",
    (Date < 2011 & Date > 2005) ~ "2005-2010",
    (Date < 2016 & Date > 2010) ~ "2010-2015",
    (Date < 2021 & Date > 2015) ~ "2015-2020",
  ))%>%
  mutate(year_ints_by_10 = case_when(
    (Date < 1981 & Date > 1970) ~ "1970-1980",
    (Date < 1991 & Date > 1980) ~ "1980-1990",
    (Date < 2001 & Date > 1990) ~ "1990-2000",
    (Date < 2011 & Date > 2000) ~ "2000-2010",
    (Date < 2021 & Date > 2010) ~ "2010-2020",
  ))%>%
  na.omit()%>%
  mutate(total_points = `Winner Pts` + `Loser Pts`)
total_points%>%
  ggplot(aes(x = year_ints_by_5, y = total_points)) + 
  geom_bar(stat = "identity") +
  stat_summary(fun.y=sum,geom="bar",colour="black",fill="#92A8D1",show.legend = FALSE) +
  labs(x = "5-Year Period", y = "Total Points", title = "Which 5-Year Period Consisted of High-Scoring Games?", subtitle = "287 points were scored between the 1990-1991 and 1994-1995 season") +
  theme_classic()+ 
    theme(axis.text.x = element_text(size = 8))



```

```{r}
total_points%>%
  ggplot(aes(x = year_ints_by_10, y = total_points)) + 
  geom_bar(stat = "identity") +
    stat_summary(fun.y=sum,geom="bar",colour="black",fill="#CC6666",show.legend = FALSE)+
  labs(x = "10-Year Period", y = "Total Points", title = "Which 10-Year Period Consisted of High-Scoring Games?", subtitle= "534 points were scored between the Superbowls of the 1990-1991 and 1999-2000 season") + 
  scale_y_continuous(breaks = seq(0, 600, by = 100)) +
  theme_classic()
```


```{r, fig.width= 20}
p = trends%>%
  ggplot(aes(x = Date), text = paste("Winner " = Winner)) + 
  geom_line(aes(y = `Winner Pts`), color = "navy", group = 1) +
  geom_line(aes(y = `Loser Pts`), color = "  dark red", group = 1) + 
  scale_x_continuous(breaks = seq(1970, 2021, by = 5)) +
  labs(x = "Year", y = "Points", title = "Trends in Super Bowl Winning and Losing Scores") + 
  theme(plot.title = element_text(size=22))  +
  theme_solarized()

ggplotly(p)
```

```{r}
modified <- superbowl%>%  
  mutate(deficit = `Winner Pts` - `Loser Pts`)%>%
  mutate(winning_division = case_when(
                            Winner %in% c('Kansas City Chiefs', 'Denver Broncos', 'Oakland Raiders', 'Los Angeles Raiders', 'San Diego Chargers') ~ 'AFC West', 
                            Winner %in% c('Chicago Bears', 'Green Bay Packers', 'Minnesota Vikings', 'Detroit Lions') ~ 'NFC North', 
                            Winner %in% c('Seattle Seahawks', 'San Francisco 49ers', 'Arizona Cardinals', 'Los Angeles Rams', 'St. Louis Rams') ~ 'NFC West', 
                            Winner %in% c('Indianapolis Colts', 'Baltimore Colts', 'Tennessee Titans', 'Houston Texans', 'Jacksonville Jaguars') ~ 'AFC South', 
                            Winner %in% c('Pittsburgh Steelers', 'Cleveland Browns', 'Cincinnati Bengals', 'Baltimore Ravens') ~ 'AFC North', 
                            Winner %in% c('New Orleans Saints', 'Carolina Panthers', 'Atlanta Falcons', 'Tampa Bay Buccaneers') ~ 'NFC South',
                            Winner %in% c('New England Patriots', 'Miami Dolphins', 'Buffalo Bills', 'New York Jets') ~ 'AFC East',
                            Winner %in% c('Dallas Cowboys', 'Philadelphia Eagles', 'New York Giants', 'Washington Redskins') ~ 'NFC East'))%>%
  mutate(losing_division = case_when(
                            Loser %in% c('Kansas City Chiefs', 'Denver Broncos', 'Oakland Raiders', 'Los Angeles Raiders', 'San Diego Chargers') ~ 'AFC West', 
                            Loser %in% c('Chicago Bears', 'Green Bay Packers', 'Minnesota Vikings', 'Detroit Lions') ~ 'NFC North', 
                            Loser %in% c('Seattle Seahawks', 'San Francisco 49ers', 'Arizona Cardinals', 'Los Angeles Rams', 'St. Louis Rams') ~ 'NFC West', 
                            Loser %in% c('Indianapolis Colts', 'Baltimore Colts', 'Tennessee Titans', 'Houston Texans', 'Jacksonville Jaguars') ~ 'AFC South', 
                            Loser %in% c('Pittsburgh Steelers', 'Cleveland Browns', 'Cincinnati Bengals', 'Baltimore Ravens') ~ 'AFC North', 
                            Loser %in% c('New Orleans Saints', 'Carolina Panthers', 'Atlanta Falcons', 'Tampa Bay Buccaneers') ~ 'NFC South',
                            Loser %in% c('New England Patriots', 'Miami Dolphins', 'Buffalo Bills', 'New York Jets') ~ 'AFC East',
                            Loser %in% c('Dallas Cowboys', 'Philadelphia Eagles', 'New York Giants', 'Washington Redskins') ~ 'NFC East'))%>%
  mutate(winning_conf = case_when(
                            winning_division %in% c('AFC West', 'AFC South', 'AFC North', 'AFC East') ~ 'AFC', 
                            winning_division %in% c('NFC West', 'NFC South', 'NFC North', 'NFC East') ~ 'NFC' 
                                ))%>%
  mutate(losing_conf = case_when(
                            losing_division %in% c('AFC West', 'AFC South', 'AFC North', 'AFC East') ~ 'AFC', 
                            losing_division %in% c('NFC West', 'NFC South', 'NFC North', 'NFC East') ~ 'NFC'))%>%
  mutate(Date = str_sub(Date, -4))

```

```{r}
windivision <- ggplot(data = modified, aes(x = winning_division, fill = winning_division)) + 
  geom_histogram(stat = "count", position="dodge")+
  scale_y_continuous(breaks = 0:15) + 
  theme(legend.position = "none", axis.text.x = element_text(size = 14)) + 
  labs(title = "Super Bowl Wins by Division", x = "Winning Division", y = "Wins") +
  theme_tufte() + 
  theme(axis.text.x = element_text(size = 13))


losedivision <- ggplot(data = modified, aes(x = losing_division, fill = losing_division)) + 
  geom_histogram(stat = "count", position="dodge")+
  scale_y_continuous(breaks = 0:15) + 
  theme(legend.position = "none") + 
  labs(title = "Super Bowl Loses by Division", x = "Losing Division", y = "Loses") +
  theme_tufte() + 
  theme(axis.text.x = element_text(size = 13))
 

conference <- ggplot(data = modified, aes(x = winning_conf, fill = winning_conf)) + 
  geom_histogram(stat = "count")+
  scale_y_continuous(breaks = 0:30) + 
  theme(legend.position = "none") + 
  scale_y_continuous(breaks = seq(0, 30, by = 1)) + 
  labs(x = "Conference", y = "Super Bowl Wins", fill = "Conference") + 
  theme_wsj() +
  theme(axis.text.y = element_text(size=8)) +
  theme(axis.title = element_text(size = 12)) + 
  theme(legend.position = "none") 


conference

```
```{r}
points_conf_win <- modified
win <- points_conf_win%>%
  select(`Winner Pts`, winning_conf)%>% 
  group_by(winning_conf)%>%
  summarise(Points = sum(`Winner Pts`))
loss <- points_conf_win%>%
  select(`Loser Pts`, losing_conf)%>% 
  group_by(losing_conf)%>%
  summarise(Points = sum(`Loser Pts`))
t <- bind_rows(win, loss)
t <- t%>%
  unite(conference, winning_conf, losing_conf)%>%
  select(conference, Points)
t[1,1] = str_sub(t[1,1], start = 0, end = 3)
t[2,1] = str_sub(t[2,1], start = 0, end = 3)
t[3,1] = str_sub(t[3,1], start = 4)
t[4,1] = str_sub(t[4,1], start = 4)
t%>%
  group_by(conference)%>%
  summarise(`Total Points` = sum(Points))%>%
  ggplot(aes(x = conference, y = `Total Points`, fill = conference)) + 
  geom_bar(stat = "identity") + 
  theme_wsj() + 
  theme(axis.title = element_text(size = 12)) + 
  scale_y_continuous(breaks = seq(0, 1500, by = 100)) + 
  labs(x = "Conference", y = "Total Points", fill = "Conference", title = "Which Conference Has Scored More Points?") + 
  theme(legend.position = "none") +
  theme(plot.title = element_text(size = 15))

```

```{r, fig.width = 10, fig.height= 10}
ggarrange(windivision, losedivision, nrow=2)  

```

```{r, fig.width=25, fig.height=5}
modified$Date = as.numeric(modified$Date)

date_div = modified%>%
  ggplot(aes(x = Date, y = `Winner Pts`, text = paste(Winner))) +
  geom_line(group = 1, alpha = 0.1) + 
  geom_point(aes(color = winning_division)) +
  theme_economist() +
  theme(legend.text = element_text(size=10)) +
    scale_colour_discrete(name = "Division") + 
  labs(title = "Trends in Winning Scores by Division")

ggplotly(date_div)

```

```{r, fig.width=20, fig.height=5}
date_div2 = modified%>%
  ggplot(aes(x = Date, y = `Loser Pts`, text = paste(Loser))) +
  geom_line(group = 1, alpha = 0.1) + 
  geom_point(aes(color = losing_division)) +
  theme_economist() +
  theme(legend.text = element_text(size=10)) + 
    scale_colour_discrete(name = "Division") + 
  labs(title = "Trends in Losing Scores by Division")

ggplotly(date_div2)


```

```{r, fig.width=30, fig.height=5}
f <- modified%>%
  ggplot(aes(x = Date, y = `Winner Pts`, text = paste(Winner))) +
  geom_point(aes(color = winning_conf)) + 
  scale_x_continuous(breaks = seq(1970, 2021, by = 5)) +
  theme_economist() +
  theme(legend.title=element_text(size=12)) +
  labs(fill = "Conference", x = "Year", y = "Winner Pts") +
  scale_colour_discrete(name = "Conference") + 
  labs(title = "Trends in Winning Scores by Conference")
ggplotly(f)
```

```{r, fig.width=30, fig.height=5}
r <- modified%>%
  ggplot(aes(x = Date, y = `Loser Pts`, text = paste(Loser))) +
  geom_point(aes(color = losing_conf)) + 
  scale_x_continuous(breaks = seq(1970, 2021, by = 5)) +
  theme_economist() +
  theme(legend.title=element_text(size=12)) +
  labs(fill = "Conference", x = "Year", y = "Loser Pts") +
  scale_colour_discrete(name = "Conference") + 
  labs(title = "Trends in Losing Scores by Conference")
ggplotly(r)
```


